require:
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - ./bin/**/*
    - ./various/**/*
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120
