FROM mcr.microsoft.com/devcontainers/ruby:3.1

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
  && apt-get install -y build-essential libsdl2-dev libsdl2-gfx-dev \
  libsdl2-image-dev libsdl2-ttf-dev
